# The URL the site will be built for
base_url = "https://awinterstein.github.io/zola-theme-project-portfolio-example"

theme = "project-portfolio"

title = "Project Portfolio"

taxonomies = [
    { name = "projects", paginate_by = 5, feed = true },
    { name = "skills", paginate_by = 5, feed = true },
    { name = "blog-tags", paginated_by = 5, feed = true },
]

[translations]
language_symbol = "🇬🇧"
home = "Home"
projects = "Projects"
skills = "Skills"
read_more = "Read More"
skills_technologies = "Skills & Technologies"
main_skills = "Main Skills"
other_skills = "Additional Skills"
words = "words"
minutes = "minutes"
slogan = "Puk Puk"
navbar_title = "Project Portfolio"
blog = "Blog"

[languages.ru]
title = "Портфолио проектов"
taxonomies = [
    { name = "projects", paginate_by = 5, feed = true },
    { name = "skills", paginate_by = 5, feed = true },
    { name = "blog-tags", paginated_by = 5, feed = true },
]

[languages.ru.translations]
language_symbol = "🇷🇺"
home = "Главная"
projects = "Проекты"
skills = "Навыки"
read_more = "Читать далее"
skills_technologies = "Навыки и технологии"
main_skills = "Основные навыки"
other_skills = "Дополнительные навыки"
words = "слова"
minutes = "минуты"
slogan = "Пук Пук"
navbar_title = "Портфолио проектов"
blog = "Блог"

[extra]
enable_multilingual = true

[extra.index]
title = "Darya Evst"
slogan = "Puk Puk"
image_avatar = "title_photo.jpg"
image_logo = "logo.png"
image_alt = "Placeholder text describing the index's image."

[extra.social]
instagram = "https://www.instagram.com/_daria_evst_"
telegram = "https://t.me/DariaEvst"
email = "puk@gmail.com"
