name: Check CSS

on:
  push:
    branches:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Tailwind CSS
        run: wget "https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.10/tailwindcss-linux-x64" -O /usr/local/bin/tailwindcss && chmod +x /usr/local/bin/tailwindcss
      - name: Verify Tailwind CSS binary
        run: echo "0c3e21d8479a4c53ffe1cfc7fe965f6b60d8cf597bdf34db132b8c65c6143541  /usr/local/bin/tailwindcss" | shasum -a 256 -b -c --strict
      - name: Generate CSS
        run: tailwindcss -i src/css/main.css -o compare.css --minify
      - name: Check for differences of committed CSS file and generated CSS file
        run: diff --brief static/css/main.css compare.css
